### ISSUE TITLE
unrelated actions mutated by consortium middleware

### ISSUE THREAD

**Issue by cdaringe** [MRN-Code/coinstac-ui#14]
<img width="1166" alt="screen shot 2015-10-15 at 6 14 51 pm" src="https://cloud.githubusercontent.com/assets/1003261/10531592/ac12bf50-7368-11e5-9cbb-621fc516742f.png">

also, we should probably move async actions to be bundled with the rest of the actions, vs. middleware

**Comment by swashcap** [comment]
Oh, crap. No good.

**Comment by cdaringe** [comment]
resolved
